version: "3"

services: 
  api:
    build: .
    ports:
      - 8000:8000
    # env_file:
    #   - ./.env
    environment:
       - DATABASE_HOSTNAME=localhost
       - DATABASE_DRIVER=SQL Server Native Client 11.0
       - DATABASE_NAME=FastApi
       - DATABASE_USERNAME=postgres
       - DATABASE_PASSWORD=December@1206
       - DATABASE_PORT=5432
       - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
       - ALGORITHM=HS256
       - ACCESS_TOKEN_EXPIRE_MINUTES=30

